server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: SOCIALUSERSERVICE
          uri: lb://SOCIALUSERSERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: CONNECTIONSERVICE
          uri: lb://CONNECTIONSERVICE
          predicates:
            - Path=/connection/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
